version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: comtel-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: comtel
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: comtel_voice
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U comtel -d comtel_voice"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: comtel_postgres_data
